//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEWorkFlow.Web.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TEWorkFlow.Web.Client.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活 的本地化字符串。
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CheckPoint in used, Delete Fail! 的本地化字符串。
        /// </summary>
        public static string CheckPonitDeleteInUsed {
            get {
                return ResourceManager.GetString("CheckPonitDeleteInUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未激活 的本地化字符串。
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        public static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Eidt {
            get {
                return ResourceManager.GetString("Eidt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误标题 的本地化字符串。
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 群组 的本地化字符串。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 群组不存在 的本地化字符串。
        /// </summary>
        public static string GroupNotExist {
            get {
                return ResourceManager.GetString("GroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息标题 的本地化字符串。
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入密码 的本地化字符串。
        /// </summary>
        public static string InputPassword {
            get {
                return ResourceManager.GetString("InputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的邮件地址 的本地化字符串。
        /// </summary>
        public static string InvaildEamil {
            get {
                return ResourceManager.GetString("InvaildEamil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoice 的本地化字符串。
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsValid 的本地化字符串。
        /// </summary>
        public static string IsValid {
            get {
                return ResourceManager.GetString("IsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录名 的本地化字符串。
        /// </summary>
        public static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块 的本地化字符串。
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        public static string NavigationMenu {
            get {
                return ResourceManager.GetString("NavigationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能为空 的本地化字符串。
        /// </summary>
        public static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未完成 的本地化字符串。
        /// </summary>
        public static string NotFinish {
            get {
                return ResourceManager.GetString("NotFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不同 的本地化字符串。
        /// </summary>
        public static string PasswordDifferent {
            get {
                return ResourceManager.GetString("PasswordDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超市保管项目 的本地化字符串。
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        public static string ReinputPassword {
            get {
                return ResourceManager.GetString("ReinputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        public static string SaveFail {
            get {
                return ResourceManager.GetString("SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户群组或子组 的本地化字符串。
        /// </summary>
        public static string UsersGroupOrSubgroup {
            get {
                return ResourceManager.GetString("UsersGroupOrSubgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的用户 的本地化字符串。
        /// </summary>
        public static string WrongUser {
            get {
                return ResourceManager.GetString("WrongUser", resourceCulture);
            }
        }
    }
}
