//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_branch_goodssale_account
    {
        public decimal rt_flow_number { get; set; }
        public string en_code { get; set; }
        public string b_code { get; set; }
        public string wh_code { get; set; }
        public string rt_date { get; set; }
        public string goods_code { get; set; }
        public string goods_bar_code { get; set; }
        public string op_code { get; set; }
        public decimal sale_price { get; set; }
        public Nullable<decimal> sale_qty { get; set; }
        public Nullable<decimal> sale_money { get; set; }
        public Nullable<decimal> discount_money { get; set; }
        public Nullable<decimal> nontax_sale_money { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public Nullable<decimal> nontax_purchase_price { get; set; }
        public Nullable<decimal> cost_money { get; set; }
        public Nullable<decimal> nontax_cost_money { get; set; }
        public Nullable<decimal> gross_money { get; set; }
        public Nullable<decimal> nontax_gross_money { get; set; }
        public string sup_code { get; set; }
        public Nullable<decimal> pool_rate { get; set; }
        public Nullable<decimal> output_tax { get; set; }
        public string if_promotion { get; set; }
    }
}
