//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_cashier_summary
    {
        public decimal rt_flow_number { get; set; }
        public string rt_date { get; set; }
        public string cashier { get; set; }
        public string rt_type { get; set; }
        public string wh_code { get; set; }
        public string b_code { get; set; }
        public string payway_code { get; set; }
        public Nullable<decimal> sale_money { get; set; }
        public Nullable<decimal> ex_rate { get; set; }
        public Nullable<decimal> pay_money { get; set; }
        public Nullable<decimal> pay_loss { get; set; }
    }
}
