//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_day_goodsstock_journal_account
    {
        public decimal ac_flow_number { get; set; }
        public string ac_date { get; set; }
        public string goods_code { get; set; }
        public string op_code { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public Nullable<decimal> nontax_purchase_price { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public Nullable<decimal> init_qty { get; set; }
        public Nullable<decimal> init_money { get; set; }
        public Nullable<decimal> init_sale_money { get; set; }
        public Nullable<decimal> purchase_qty { get; set; }
        public Nullable<decimal> purchase_money { get; set; }
        public Nullable<decimal> purchase_sale_money { get; set; }
        public Nullable<decimal> return_qty { get; set; }
        public Nullable<decimal> return_money { get; set; }
        public Nullable<decimal> return_sale_money { get; set; }
        public Nullable<decimal> sale_qty { get; set; }
        public Nullable<decimal> sale_money { get; set; }
        public Nullable<decimal> nontax_sale_money { get; set; }
        public Nullable<decimal> supply_qty { get; set; }
        public Nullable<decimal> supply_money { get; set; }
        public Nullable<decimal> supply_sale_money { get; set; }
        public Nullable<decimal> sreturn_qty { get; set; }
        public Nullable<decimal> sreturn_money { get; set; }
        public Nullable<decimal> sreturn_sale_money { get; set; }
        public Nullable<decimal> loss_qty { get; set; }
        public Nullable<decimal> loss_money { get; set; }
        public Nullable<decimal> loss_sale_money { get; set; }
        public Nullable<decimal> adjust_qty { get; set; }
        public Nullable<decimal> adjust_money { get; set; }
        public Nullable<decimal> adjust_sale_money { get; set; }
        public Nullable<decimal> gross_money { get; set; }
        public Nullable<decimal> nontax_gross_money { get; set; }
        public Nullable<decimal> adjustsale_money { get; set; }
        public Nullable<decimal> stock_qty { get; set; }
        public Nullable<decimal> stock_money { get; set; }
        public Nullable<decimal> stock_sale_money { get; set; }
        public string sup_code { get; set; }
    }
}
