//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_month_class_journal_account
    {
        public decimal ac_flow_number { get; set; }
        public string ac_month { get; set; }
        public string goods_class_code { get; set; }
        public Nullable<decimal> init_qty { get; set; }
        public Nullable<decimal> init_money { get; set; }
        public Nullable<decimal> nontax_init_money { get; set; }
        public Nullable<decimal> purchase_qty { get; set; }
        public Nullable<decimal> purchase_money { get; set; }
        public Nullable<decimal> nontax_purchase_money { get; set; }
        public Nullable<decimal> return_qty { get; set; }
        public Nullable<decimal> return_money { get; set; }
        public Nullable<decimal> nontax_return_money { get; set; }
        public Nullable<decimal> sale_qty { get; set; }
        public Nullable<decimal> sale_money { get; set; }
        public Nullable<decimal> nontax_sale_money { get; set; }
        public Nullable<decimal> alin_qty { get; set; }
        public Nullable<decimal> alin_money { get; set; }
        public Nullable<decimal> nontax_alin_money { get; set; }
        public Nullable<decimal> alout_qty { get; set; }
        public Nullable<decimal> alout_money { get; set; }
        public Nullable<decimal> nontax_alout_money { get; set; }
        public Nullable<decimal> loss_qty { get; set; }
        public Nullable<decimal> loss_money { get; set; }
        public Nullable<decimal> nontax_loss_money { get; set; }
        public Nullable<decimal> adjust_money { get; set; }
        public Nullable<decimal> nontax_adjust_money { get; set; }
        public Nullable<decimal> gross_money { get; set; }
        public Nullable<decimal> nontax_gross_money { get; set; }
        public Nullable<decimal> stock_qty { get; set; }
        public Nullable<decimal> stock_money { get; set; }
        public Nullable<decimal> nontax_stock_money { get; set; }
    }
}
