//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_pa_saleset
    {
        public Nullable<System.DateTime> last_ty_date { get; set; }
        public Nullable<decimal> last_sa_flow_number { get; set; }
        public Nullable<decimal> current_sa_flow_number { get; set; }
        public string Id { get; set; }
    }
}
