//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_pa_dayaccount
    {
        public Nullable<System.DateTime> last_ty_date { get; set; }
        public Nullable<decimal> last_rt_flow_number { get; set; }
        public Nullable<decimal> current_rt_flow_number { get; set; }
        public Nullable<decimal> last_ws_flow_number { get; set; }
        public Nullable<decimal> current_ws_flow_number { get; set; }
        public Nullable<decimal> last_pi_flow_number { get; set; }
        public Nullable<decimal> current_pi_flow_number { get; set; }
        public Nullable<decimal> last_po_flow_number { get; set; }
        public Nullable<decimal> current_po_flow_number { get; set; }
        public Nullable<decimal> last_al_flow_number { get; set; }
        public Nullable<decimal> current_al_flow_number { get; set; }
        public Nullable<decimal> last_lo_flow_number { get; set; }
        public Nullable<decimal> current_lo_flow_number { get; set; }
        public Nullable<decimal> last_ad_flow_number { get; set; }
        public Nullable<decimal> current_ad_flow_number { get; set; }
        public Nullable<decimal> last_ex_flow_number { get; set; }
        public Nullable<decimal> current_ex_flow_number { get; set; }
        public Nullable<decimal> last_sc_flow_number { get; set; }
        public Nullable<decimal> current_sc_flow_number { get; set; }
        public Nullable<decimal> last_sp_flow_number { get; set; }
        public Nullable<decimal> current_sp_flow_number { get; set; }
        public Nullable<decimal> last_re_flow_number { get; set; }
        public Nullable<decimal> current_re_flow_number { get; set; }
        public string Id { get; set; }
    }
}
