//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_stock_account
    {
        public string en_code { get; set; }
        public string wh_code { get; set; }
        public string goods_code { get; set; }
        public string sup_code { get; set; }
        public Nullable<decimal> stock_qty { get; set; }
        public Nullable<decimal> stock_money { get; set; }
        public Nullable<decimal> nontax_stock_money { get; set; }
        public string Id { get; set; }
    }
}
