//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_branch_detail
    {
        public string ba_number { get; set; }
        public string operat_number { get; set; }
        public string operat_type { get; set; }
        public Nullable<decimal> receivable_money { get; set; }
        public Nullable<decimal> received_money { get; set; }
        public Nullable<decimal> unreceived_money { get; set; }
        public Nullable<decimal> pay_money { get; set; }
        public Nullable<decimal> pay_margin { get; set; }
        public string margin_deal { get; set; }
        public string table_name { get; set; }
        public string column_name { get; set; }
        public string Id { get; set; }
    }
}
