//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_pa_subject
    {
        public decimal ba_flow_number { get; set; }
        public string operat_type { get; set; }
        public string op_code { get; set; }
        public string s_number { get; set; }
        public string debit_credit { get; set; }
        public Nullable<decimal> input_tax { get; set; }
        public string subject_code { get; set; }
        public string if_tax { get; set; }
        public string if_dept { get; set; }
        public string if_supplier { get; set; }
        public string if_kind { get; set; }
        public string if_rate { get; set; }
        public string if_antitone { get; set; }
    }
}
