//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class bs_supply_detail
    {
        public string sp_number { get; set; }
        public string wh_code { get; set; }
        public string b_code { get; set; }
        public string sp_state { get; set; }
        public string wh_code_out { get; set; }
        public string goods_bar_code { get; set; }
        public string goods_code { get; set; }
        public string specification { get; set; }
        public string pack_unit_code { get; set; }
        public Nullable<decimal> purchase_pack_qty { get; set; }
        public Nullable<decimal> supply_pack_qty { get; set; }
        public Nullable<decimal> putin_pack_qty { get; set; }
        public Nullable<decimal> pack_coef { get; set; }
        public Nullable<decimal> purchase_qty { get; set; }
        public Nullable<decimal> supply_qty { get; set; }
        public Nullable<decimal> putin_qty { get; set; }
        public Nullable<decimal> supply_price { get; set; }
        public Nullable<decimal> supply_money { get; set; }
        public Nullable<decimal> discount_money { get; set; }
        public string sys_guid { get; set; }
        public string Id { get; set; }
    }
}
