//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class bs_supply_present_promotion_goods
    {
        public string sp_number { get; set; }
        public string sp_begin_date { get; set; }
        public string sp_end_date { get; set; }
        public string goods_bar_code { get; set; }
        public string goods_code { get; set; }
        public Nullable<decimal> supply_qty { get; set; }
        public Nullable<decimal> supply_price { get; set; }
        public string goods_bar_code_present { get; set; }
        public string goods_code_present { get; set; }
        public Nullable<decimal> present_qty { get; set; }
        public Nullable<decimal> present_money { get; set; }
        public string sys_guid { get; set; }
        public string Id { get; set; }
    }
}
