//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class em_employee_archives
    {
        public em_employee_archives()
        {
            this.em_employee_family = new HashSet<em_employee_family>();
        }
    
        public string em_code { get; set; }
        public string em_name { get; set; }
        public string name_used { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string sex { get; set; }
        public string politics_code { get; set; }
        public string nation_code { get; set; }
        public string education_code { get; set; }
        public string Professional_title_code { get; set; }
        public string if_married { get; set; }
        public string native_place { get; set; }
        public string idcard { get; set; }
        public Nullable<System.DateTime> accede_day { get; set; }
        public string family_phone { get; set; }
        public string handset { get; set; }
        public string e_mail { get; set; }
        public string family_address { get; set; }
        public string postalcode { get; set; }
        public string graduate_academy { get; set; }
        public Nullable<System.DateTime> graduate_day { get; set; }
        public string d_code { get; set; }
        public string b_code { get; set; }
        public string duty_code { get; set; }
        public string bank_account { get; set; }
        public string pension_account { get; set; }
        public string em_state { get; set; }
        public Nullable<decimal> stature { get; set; }
        public Nullable<decimal> width { get; set; }
    
        public virtual ICollection<em_employee_family> em_employee_family { get; set; }
    }
}
