//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class fb_supplier_archives
    {
        public string sup_code { get; set; }
        public string sup_name { get; set; }
        public string py_code { get; set; }
        public string sup_type_code { get; set; }
        public string functionary { get; set; }
        public string functionary_phone { get; set; }
        public string linkman { get; set; }
        public string contact_phone { get; set; }
        public string contact_address { get; set; }
        public string office_phone { get; set; }
        public string fax_phone { get; set; }
        public string e_mail { get; set; }
        public string postalcode { get; set; }
        public string open_account { get; set; }
        public string bank_account { get; set; }
        public string tax_number { get; set; }
        public string op_code { get; set; }
        public string stock_voucher { get; set; }
        public Nullable<decimal> input_tax { get; set; }
        public string balance_mode { get; set; }
        public string pay_mode { get; set; }
        public string balance_period { get; set; }
        public Nullable<decimal> balance_day { get; set; }
        public string offer_mode { get; set; }
        public Nullable<decimal> delivery_days { get; set; }
        public Nullable<decimal> pool_rate { get; set; }
        public Nullable<decimal> floors_money { get; set; }
        public Nullable<decimal> excess_rate { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string @operator { get; set; }
        public string assessor { get; set; }
        public string if_examine { get; set; }
        public Nullable<System.DateTime> examine_date { get; set; }
        public Nullable<System.DateTime> operator_date { get; set; }
    }
}
