//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class YiQiEntities : DbContext
    {
        private static string getConnectionString()
        {
            NameValueCollection cfgName = (NameValueCollection)ConfigurationSettings.GetConfig("databaseSettings");
            string connStr = cfgName["db.connectionString"].ToString();
            return string.Format(
            "metadata=res://*/Basement.Model.csdl|res://*/Basement.Model.ssdl|res://*/Basement.Model.msl;provider=System.Data.SqlClient;provider connection string=\"{0};MultipleActiveResultSets=True;App=EntityFramework\"",
            connStr);

        }

        public YiQiEntities()
            : base(getConnectionString())
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<ac_branch_goodssale_account> ac_branch_goodssale_account { get; set; }
        public DbSet<ac_cashier_summary> ac_cashier_summary { get; set; }
        public DbSet<ac_counter_summary> ac_counter_summary { get; set; }
        public DbSet<ac_day_branchclass_journal_account> ac_day_branchclass_journal_account { get; set; }
        public DbSet<ac_day_branchgoods_journal_account> ac_day_branchgoods_journal_account { get; set; }
        public DbSet<ac_day_class_journal_account> ac_day_class_journal_account { get; set; }
        public DbSet<ac_day_goods_journal_account> ac_day_goods_journal_account { get; set; }
        public DbSet<ac_day_goods_journal_account_temp> ac_day_goods_journal_account_temp { get; set; }
        public DbSet<ac_day_goodsstock_journal_account> ac_day_goodsstock_journal_account { get; set; }
        public DbSet<ac_day_goodsstock_journal_account_temp> ac_day_goodsstock_journal_account_temp { get; set; }
        public DbSet<ac_goodssale_account> ac_goodssale_account { get; set; }
        public DbSet<ac_goodssale_account_tg> ac_goodssale_account_tg { get; set; }
        public DbSet<ac_month_class_journal_account> ac_month_class_journal_account { get; set; }
        public DbSet<ac_month_goods_journal_account> ac_month_goods_journal_account { get; set; }
        public DbSet<ac_pa_dayaccount> ac_pa_dayaccount { get; set; }
        public DbSet<ac_pa_dayaccount_stock> ac_pa_dayaccount_stock { get; set; }
        public DbSet<ac_pa_saleset> ac_pa_saleset { get; set; }
        public DbSet<ac_period_time_summary> ac_period_time_summary { get; set; }
        public DbSet<ac_salesman_summary> ac_salesman_summary { get; set; }
        public DbSet<ac_stock_account> ac_stock_account { get; set; }
        public DbSet<ac_supplier_journal> ac_supplier_journal { get; set; }
        public DbSet<ba_branch_balance> ba_branch_balance { get; set; }
        public DbSet<ba_branch_detail> ba_branch_detail { get; set; }
        public DbSet<ba_branch_offer_account> ba_branch_offer_account { get; set; }
        public DbSet<ba_branch_offer_detail> ba_branch_offer_detail { get; set; }
        public DbSet<ba_charge_detail> ba_charge_detail { get; set; }
        public DbSet<ba_charge_manage> ba_charge_manage { get; set; }
        public DbSet<ba_customer_balance> ba_customer_balance { get; set; }
        public DbSet<ba_customer_detail> ba_customer_detail { get; set; }
        public DbSet<ba_lease_account> ba_lease_account { get; set; }
        public DbSet<ba_lease_detail> ba_lease_detail { get; set; }
        public DbSet<ba_offer_account> ba_offer_account { get; set; }
        public DbSet<ba_offer_detail> ba_offer_detail { get; set; }
        public DbSet<ba_pa_account> ba_pa_account { get; set; }
        public DbSet<ba_pa_branch_account> ba_pa_branch_account { get; set; }
        public DbSet<ba_pa_charge> ba_pa_charge { get; set; }
        public DbSet<ba_pa_subject> ba_pa_subject { get; set; }
        public DbSet<ba_pool_account> ba_pool_account { get; set; }
        public DbSet<ba_pool_detail> ba_pool_detail { get; set; }
        public DbSet<ba_supplier_balance> ba_supplier_balance { get; set; }
        public DbSet<ba_supplier_detail> ba_supplier_detail { get; set; }
        public DbSet<bs_adjust_saleprice> bs_adjust_saleprice { get; set; }
        public DbSet<bs_adjust_saleprice_goods> bs_adjust_saleprice_goods { get; set; }
        public DbSet<bs_branch_allot_detail> bs_branch_allot_detail { get; set; }
        public DbSet<bs_branch_allot_manage> bs_branch_allot_manage { get; set; }
        public DbSet<bs_branch_archives> bs_branch_archives { get; set; }
        public DbSet<bs_branch_price> bs_branch_price { get; set; }
        public DbSet<bs_pa_area> bs_pa_area { get; set; }
        public DbSet<bs_pa_branch_warehouse> bs_pa_branch_warehouse { get; set; }
        public DbSet<bs_pa_class> bs_pa_class { get; set; }
        public DbSet<bs_return_detail> bs_return_detail { get; set; }
        public DbSet<bs_return_manage> bs_return_manage { get; set; }
        public DbSet<bs_return_manage_flow> bs_return_manage_flow { get; set; }
        public DbSet<bs_supply_detail> bs_supply_detail { get; set; }
        public DbSet<bs_supply_manage> bs_supply_manage { get; set; }
        public DbSet<bs_supply_manage_flow> bs_supply_manage_flow { get; set; }
        public DbSet<bs_supply_present_promotion> bs_supply_present_promotion { get; set; }
        public DbSet<bs_supply_present_promotion_branch> bs_supply_present_promotion_branch { get; set; }
        public DbSet<bs_supply_present_promotion_goods> bs_supply_present_promotion_goods { get; set; }
        public DbSet<bs_supply_promotion> bs_supply_promotion { get; set; }
        public DbSet<bs_supply_promotion_branch> bs_supply_promotion_branch { get; set; }
        public DbSet<bs_supply_promotion_goods> bs_supply_promotion_goods { get; set; }
        public DbSet<dtproperties> dtproperties { get; set; }
        public DbSet<em_employee_archives> em_employee_archives { get; set; }
        public DbSet<em_employee_family> em_employee_family { get; set; }
        public DbSet<em_employee_photo> em_employee_photo { get; set; }
        public DbSet<em_pa_duty> em_pa_duty { get; set; }
        public DbSet<em_pa_education> em_pa_education { get; set; }
        public DbSet<em_pa_nation> em_pa_nation { get; set; }
        public DbSet<em_pa_politics> em_pa_politics { get; set; }
        public DbSet<em_pa_Professional_title> em_pa_Professional_title { get; set; }
        public DbSet<fb_adjust_class> fb_adjust_class { get; set; }
        public DbSet<fb_adjust_class_goods> fb_adjust_class_goods { get; set; }
        public DbSet<fb_adjust_poolrate> fb_adjust_poolrate { get; set; }
        public DbSet<fb_adjust_poolrate_goods> fb_adjust_poolrate_goods { get; set; }
        public DbSet<fb_adjust_purchaseprice> fb_adjust_purchaseprice { get; set; }
        public DbSet<fb_adjust_purchaseprice_goods> fb_adjust_purchaseprice_goods { get; set; }
        public DbSet<fb_adjust_saleprice> fb_adjust_saleprice { get; set; }
        public DbSet<fb_adjust_saleprice_goods> fb_adjust_saleprice_goods { get; set; }
        public DbSet<fb_adjust_supplier> fb_adjust_supplier { get; set; }
        public DbSet<fb_adjust_supplier_goods> fb_adjust_supplier_goods { get; set; }
        public DbSet<fb_goods_archives> fb_goods_archives { get; set; }
        public DbSet<fb_goods_archives_bar> fb_goods_archives_bar { get; set; }
        public DbSet<fb_goods_archives_bind> fb_goods_archives_bind { get; set; }
        public DbSet<fb_goods_archives_library> fb_goods_archives_library { get; set; }
        public DbSet<fb_goods_archives_parts> fb_goods_archives_parts { get; set; }
        public DbSet<fb_goods_archives_photo> fb_goods_archives_photo { get; set; }
        public DbSet<fb_goods_archives_supplier> fb_goods_archives_supplier { get; set; }
        public DbSet<fb_goods_bar_code> fb_goods_bar_code { get; set; }
        public DbSet<fb_pa_base_set> fb_pa_base_set { get; set; }
        public DbSet<fb_pa_goods_brand> fb_pa_goods_brand { get; set; }
        public DbSet<fb_pa_goods_check_unit> fb_pa_goods_check_unit { get; set; }
        public DbSet<fb_pa_goods_counter> fb_pa_goods_counter { get; set; }
        public DbSet<fb_pa_goods_gb> fb_pa_goods_gb { get; set; }
        public DbSet<fb_pa_goods_gl> fb_pa_goods_gl { get; set; }
        public DbSet<fb_pa_goods_gm> fb_pa_goods_gm { get; set; }
        public DbSet<fb_pa_goods_gs> fb_pa_goods_gs { get; set; }
        public DbSet<fb_pa_goods_pack_unit> fb_pa_goods_pack_unit { get; set; }
        public DbSet<fb_pa_sup_type> fb_pa_sup_type { get; set; }
        public DbSet<fb_supplier_archives> fb_supplier_archives { get; set; }
        public DbSet<fb_supplier_lease> fb_supplier_lease { get; set; }
        public DbSet<ms_adjust_points> ms_adjust_points { get; set; }
        public DbSet<ms_cancel_card_manage> ms_cancel_card_manage { get; set; }
        public DbSet<ms_card_archives> ms_card_archives { get; set; }
        public DbSet<ms_cardtype_discount> ms_cardtype_discount { get; set; }
        public DbSet<ms_cardtype_goods_discount> ms_cardtype_goods_discount { get; set; }
        public DbSet<ms_cardtype_goods_points> ms_cardtype_goods_points { get; set; }
        public DbSet<ms_cardtype_manage> ms_cardtype_manage { get; set; }
        public DbSet<ms_cardtype_points> ms_cardtype_points { get; set; }
        public DbSet<ms_exchange_detail> ms_exchange_detail { get; set; }
        public DbSet<ms_exchange_manage> ms_exchange_manage { get; set; }
        public DbSet<ms_freeze_card_manage> ms_freeze_card_manage { get; set; }
        public DbSet<ms_gift_archives> ms_gift_archives { get; set; }
        public DbSet<ms_grant_card_manage> ms_grant_card_manage { get; set; }
        public DbSet<ms_loss_card_manage> ms_loss_card_manage { get; set; }
        public DbSet<ms_madecard_manage> ms_madecard_manage { get; set; }
        public DbSet<ms_member_archives> ms_member_archives { get; set; }
        public DbSet<ms_points_clear> ms_points_clear { get; set; }
        public DbSet<ms_pointtoprepaid_manage> ms_pointtoprepaid_manage { get; set; }
        public DbSet<ms_prepaid_card_manage> ms_prepaid_card_manage { get; set; }
        public DbSet<ms_reclaim_card_manage> ms_reclaim_card_manage { get; set; }
        public DbSet<ms_update_card_manage> ms_update_card_manage { get; set; }
        public DbSet<ms_upgrade_card_detail> ms_upgrade_card_detail { get; set; }
        public DbSet<ms_upgrade_card_manage> ms_upgrade_card_manage { get; set; }
        public DbSet<op_adjust_detail> op_adjust_detail { get; set; }
        public DbSet<op_adjust_manage> op_adjust_manage { get; set; }
        public DbSet<op_adjust_manage_flow> op_adjust_manage_flow { get; set; }
        public DbSet<op_adjust_purchase_detail> op_adjust_purchase_detail { get; set; }
        public DbSet<op_adjust_purchase_manage> op_adjust_purchase_manage { get; set; }
        public DbSet<op_allot_detail> op_allot_detail { get; set; }
        public DbSet<op_allot_manage> op_allot_manage { get; set; }
        public DbSet<op_allot_manage_flow> op_allot_manage_flow { get; set; }
        public DbSet<op_check_detail> op_check_detail { get; set; }
        public DbSet<op_check_manage> op_check_manage { get; set; }
        public DbSet<op_check_stock> op_check_stock { get; set; }
        public DbSet<op_check_transfer> op_check_transfer { get; set; }
        public DbSet<op_dynamic_stock> op_dynamic_stock { get; set; }
        public DbSet<op_dynamic_stock_branch> op_dynamic_stock_branch { get; set; }
        public DbSet<op_dynamic_stock_wh> op_dynamic_stock_wh { get; set; }
        public DbSet<op_goods_batch> op_goods_batch { get; set; }
        public DbSet<op_loss_detail> op_loss_detail { get; set; }
        public DbSet<op_loss_manage> op_loss_manage { get; set; }
        public DbSet<op_loss_manage_flow> op_loss_manage_flow { get; set; }
        public DbSet<op_pa_warehouse> op_pa_warehouse { get; set; }
        public DbSet<op_split_com_detail> op_split_com_detail { get; set; }
        public DbSet<op_split_com_goods> op_split_com_goods { get; set; }
        public DbSet<op_split_com_manage> op_split_com_manage { get; set; }
        public DbSet<op_split_com_manage_flow> op_split_com_manage_flow { get; set; }
        public DbSet<pbcatedt> pbcatedt { get; set; }
        public DbSet<pbcatfmt> pbcatfmt { get; set; }
        public DbSet<pbcatvld> pbcatvld { get; set; }
        public DbSet<pc_purchase_detail> pc_purchase_detail { get; set; }
        public DbSet<pc_purchase_manage> pc_purchase_manage { get; set; }
        public DbSet<pc_putin_detail> pc_putin_detail { get; set; }
        public DbSet<pc_putin_manage> pc_putin_manage { get; set; }
        public DbSet<pc_putout_detail> pc_putout_detail { get; set; }
        public DbSet<pc_putout_manage> pc_putout_manage { get; set; }
        public DbSet<pc_return_detail> pc_return_detail { get; set; }
        public DbSet<pc_return_manage> pc_return_manage { get; set; }
        public DbSet<rt_class_promotion> rt_class_promotion { get; set; }
        public DbSet<rt_class_promotion_branch> rt_class_promotion_branch { get; set; }
        public DbSet<rt_class_promotion_goods> rt_class_promotion_goods { get; set; }
        public DbSet<rt_pa_function> rt_pa_function { get; set; }
        public DbSet<rt_pa_payway> rt_pa_payway { get; set; }
        public DbSet<rt_pa_pos> rt_pa_pos { get; set; }
        public DbSet<rt_pa_saleset> rt_pa_saleset { get; set; }
        public DbSet<rt_pa_shift> rt_pa_shift { get; set; }
        public DbSet<rt_plu_promotion> rt_plu_promotion { get; set; }
        public DbSet<rt_plu_promotion_branch> rt_plu_promotion_branch { get; set; }
        public DbSet<rt_plu_promotion_goods> rt_plu_promotion_goods { get; set; }
        public DbSet<rt_present_promotion> rt_present_promotion { get; set; }
        public DbSet<rt_present_promotion_branch> rt_present_promotion_branch { get; set; }
        public DbSet<rt_present_promotion_goods> rt_present_promotion_goods { get; set; }
        public DbSet<rt_retail_detail> rt_retail_detail { get; set; }
        public DbSet<rt_retail_log> rt_retail_log { get; set; }
        public DbSet<rt_retail_manage> rt_retail_manage { get; set; }
        public DbSet<rt_retail_pay> rt_retail_pay { get; set; }
        public DbSet<rt_sheet_promotion> rt_sheet_promotion { get; set; }
        public DbSet<rt_sheet_promotion_branch> rt_sheet_promotion_branch { get; set; }
        public DbSet<rt_sheet_promotion_goods> rt_sheet_promotion_goods { get; set; }
        public DbSet<sys_class_power> sys_class_power { get; set; }
        public DbSet<sys_depart_power> sys_depart_power { get; set; }
        public DbSet<sys_enterprise_archives> sys_enterprise_archives { get; set; }
        public DbSet<sys_login_power> sys_login_power { get; set; }
        public DbSet<sys_login_power_function> sys_login_power_function { get; set; }
        public DbSet<sys_module> sys_module { get; set; }
        public DbSet<sys_module_content> sys_module_content { get; set; }
        public DbSet<sys_module_pic> sys_module_pic { get; set; }
        public DbSet<sys_operation_flow> sys_operation_flow { get; set; }
        public DbSet<sys_operation_flow_detail> sys_operation_flow_detail { get; set; }
        public DbSet<sys_operation_flow_detail_max> sys_operation_flow_detail_max { get; set; }
        public DbSet<sys_operation_worker> sys_operation_worker { get; set; }
        public DbSet<sys_pa_department> sys_pa_department { get; set; }
        public DbSet<sys_print_design> sys_print_design { get; set; }
        public DbSet<sys_SerialNumber> sys_SerialNumber { get; set; }
        public DbSet<sys_worker_power> sys_worker_power { get; set; }
        public DbSet<tf_data_download> tf_data_download { get; set; }
        public DbSet<tf_data_object> tf_data_object { get; set; }
        public DbSet<tf_data_property> tf_data_property { get; set; }
        public DbSet<tg_expostor_balance> tg_expostor_balance { get; set; }
        public DbSet<tg_expostor_balance_detail> tg_expostor_balance_detail { get; set; }
        public DbSet<tg_group_balance> tg_group_balance { get; set; }
        public DbSet<tg_group_balance_detail> tg_group_balance_detail { get; set; }
        public DbSet<tg_group_call> tg_group_call { get; set; }
        public DbSet<tg_guide_archives> tg_guide_archives { get; set; }
        public DbSet<tg_guide_balance> tg_guide_balance { get; set; }
        public DbSet<tg_guide_balance_detail> tg_guide_balance_detail { get; set; }
        public DbSet<tg_pa_cars_charge> tg_pa_cars_charge { get; set; }
        public DbSet<tg_pa_cars_type> tg_pa_cars_type { get; set; }
        public DbSet<tg_pa_group> tg_pa_group { get; set; }
        public DbSet<tg_pa_group_type> tg_pa_group_type { get; set; }
        public DbSet<tg_pa_ta_type> tg_pa_ta_type { get; set; }
        public DbSet<tg_pushtac_detail> tg_pushtac_detail { get; set; }
        public DbSet<tg_pushtac_manage> tg_pushtac_manage { get; set; }
        public DbSet<tg_tourgroup_manage> tg_tourgroup_manage { get; set; }
        public DbSet<tg_travel_archives> tg_travel_archives { get; set; }
        public DbSet<tg_travel_archives_pushtac> tg_travel_archives_pushtac { get; set; }
        public DbSet<tg_travel_balance> tg_travel_balance { get; set; }
        public DbSet<tg_travel_balance_detail> tg_travel_balance_detail { get; set; }
        public DbSet<ws_customer_archives> ws_customer_archives { get; set; }
        public DbSet<ws_customer_goods> ws_customer_goods { get; set; }
        public DbSet<ws_order_detail> ws_order_detail { get; set; }
        public DbSet<ws_order_manage> ws_order_manage { get; set; }
        public DbSet<ws_pa_customer_type> ws_pa_customer_type { get; set; }
        public DbSet<ws_wholesale_detail> ws_wholesale_detail { get; set; }
        public DbSet<ws_wholesale_goods_set> ws_wholesale_goods_set { get; set; }
        public DbSet<ws_wholesale_manage> ws_wholesale_manage { get; set; }
        public DbSet<ws_wholesale_manage_flow> ws_wholesale_manage_flow { get; set; }
    }
}
