//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_cardtype_manage
    {
        public string card_code { get; set; }
        public string card_name { get; set; }
        public string card_type { get; set; }
        public string card_medium { get; set; }
        public Nullable<decimal> card_useful_life { get; set; }
        public Nullable<decimal> points_useful_life { get; set; }
        public Nullable<decimal> transact_charge { get; set; }
        public Nullable<decimal> deposit_money { get; set; }
        public string if_vip { get; set; }
        public string if_discount { get; set; }
        public Nullable<decimal> discount_base { get; set; }
        public Nullable<decimal> discount_rate { get; set; }
        public string if_points { get; set; }
        public Nullable<decimal> expend_base { get; set; }
        public Nullable<decimal> points_values { get; set; }
        public Nullable<decimal> birthday_points { get; set; }
        public string if_prepaid { get; set; }
        public string if_prepaid_password { get; set; }
        public Nullable<decimal> limit_times { get; set; }
        public Nullable<decimal> prestore_money { get; set; }
        public string prestore_pw { get; set; }
        public Nullable<decimal> prepaid_min { get; set; }
        public Nullable<decimal> prepaid_max { get; set; }
        public string if_point_to_prepaid { get; set; }
        public Nullable<decimal> points_base { get; set; }
        public Nullable<decimal> prepaid_money { get; set; }
        public string card_number_prefix { get; set; }
        public Nullable<decimal> card_number_len { get; set; }
        public Nullable<decimal> rand_len { get; set; }
        public string upgrade_type { get; set; }
        public Nullable<decimal> points_needs { get; set; }
        public string if_deduct_points { get; set; }
        public string if_autoup { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string @operator { get; set; }
        public string assessor { get; set; }
        public string if_examine { get; set; }
        public Nullable<System.DateTime> examine_date { get; set; }
        public Nullable<System.DateTime> operator_date { get; set; }
    }
}
