//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_exchange_detail
    {
        public string exchange_number { get; set; }
        public Nullable<decimal> s_number { get; set; }
        public string goods_code { get; set; }
        public string goods_name { get; set; }
        public Nullable<decimal> exchange_qty { get; set; }
        public Nullable<decimal> exchange_points { get; set; }
        public Nullable<decimal> points_total { get; set; }
        public Nullable<decimal> gross_money { get; set; }
        public Nullable<decimal> nontax_gross_money { get; set; }
        public string sys_guid { get; set; }
        public string Id { get; set; }
    }
}
