//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_madecard_manage
    {
        public string md_number { get; set; }
        public Nullable<System.DateTime> md_date { get; set; }
        public string card_code { get; set; }
        public Nullable<decimal> begin_card_number { get; set; }
        public Nullable<decimal> end_card_number { get; set; }
        public Nullable<decimal> made_qty { get; set; }
        public string effective_type { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public string if_made { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string @operator { get; set; }
        public string assessor { get; set; }
        public string if_examine { get; set; }
        public Nullable<System.DateTime> examine_date { get; set; }
        public Nullable<System.DateTime> operator_date { get; set; }
    }
}
