//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_member_archives
    {
        public string card_number { get; set; }
        public string ms_code { get; set; }
        public string ms_name { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string sex { get; set; }
        public string politics_code { get; set; }
        public string nation_code { get; set; }
        public string education_code { get; set; }
        public string Professional_title_code { get; set; }
        public string if_married { get; set; }
        public string native_place { get; set; }
        public string idcard { get; set; }
        public string family_phone { get; set; }
        public string handset { get; set; }
        public string e_mail { get; set; }
        public string family_address { get; set; }
        public string postalcode { get; set; }
        public Nullable<decimal> stature { get; set; }
        public Nullable<decimal> width { get; set; }
    }
}
