//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_retail_detail
    {
        public decimal sa_flow_number { get; set; }
        public string rt_number { get; set; }
        public string s_number { get; set; }
        public Nullable<System.DateTime> rt_date { get; set; }
        public string rt_type { get; set; }
        public string wh_code { get; set; }
        public string b_code { get; set; }
        public string posid { get; set; }
        public string goods_code { get; set; }
        public string goods_bar_code { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public Nullable<decimal> real_price { get; set; }
        public Nullable<decimal> sale_qty { get; set; }
        public Nullable<decimal> sale_money { get; set; }
        public Nullable<decimal> discount_money { get; set; }
        public Nullable<decimal> purchase_qty { get; set; }
        public Nullable<decimal> p_sale_price { get; set; }
        public Nullable<decimal> p_sale_money { get; set; }
        public Nullable<decimal> p_discount_money { get; set; }
        public string cashier { get; set; }
        public string salesman { get; set; }
        public string under_counter_code { get; set; }
        public Nullable<decimal> pool_rate { get; set; }
        public Nullable<System.DateTime> shift_date { get; set; }
        public string if_promotion { get; set; }
        public string owner_type { get; set; }
        public string sys_guid { get; set; }
    }
}
