//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Report
    {
        public Sys_Report()
        {
            this.Sys_Report_Column = new HashSet<Sys_Report_Column>();
            this.Sys_Report_Marks = new HashSet<Sys_Report_Marks>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string TableName { get; set; }
        public string SubTableName { get; set; }
        public string DataUrl { get; set; }
        public string OutKey { get; set; }
        public string Header1 { get; set; }
        public string Header2 { get; set; }
        public string Header3 { get; set; }
        public string Footer1 { get; set; }
        public string Footer2 { get; set; }
        public string Footer3 { get; set; }
    
        public virtual ICollection<Sys_Report_Column> Sys_Report_Column { get; set; }
        public virtual ICollection<Sys_Report_Marks> Sys_Report_Marks { get; set; }
    }
}
