//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_print_design
    {
        public string dw_object { get; set; }
        public string template_name { get; set; }
        public string if_main { get; set; }
        public string data_object { get; set; }
        public string ob_content { get; set; }
        public string ob_font_face { get; set; }
        public Nullable<decimal> ob_font_height { get; set; }
        public Nullable<decimal> ob_font_weight { get; set; }
        public string ob_font_italic { get; set; }
        public string ob_font_underline { get; set; }
        public Nullable<decimal> ob_color { get; set; }
        public string if_visible { get; set; }
        public Nullable<decimal> ob_x { get; set; }
        public Nullable<decimal> ob_y { get; set; }
        public Nullable<decimal> ob_width { get; set; }
        public Nullable<decimal> ob_height { get; set; }
        public string Id { get; set; }
    }
}
