//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tg_guide_archives
    {
        public decimal tg_flow_number { get; set; }
        public string guide_code { get; set; }
        public string guide_name { get; set; }
        public string py_code { get; set; }
        public string guide_type { get; set; }
        public string guide_id { get; set; }
        public string contact_phone { get; set; }
        public string ta_code { get; set; }
        public string ta_name { get; set; }
        public string tac_code { get; set; }
        public Nullable<decimal> push_rate { get; set; }
        public Nullable<decimal> push_money { get; set; }
        public string license_plate { get; set; }
        public string comment { get; set; }
    }
}
