//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tg_travel_balance_detail
    {
        public string ba_number { get; set; }
        public string s_number { get; set; }
        public string ba_nopay_number { get; set; }
        public string group_number { get; set; }
        public Nullable<System.DateTime> sale_date { get; set; }
        public string ba_items { get; set; }
        public string gb_code { get; set; }
        public string guide_code { get; set; }
        public Nullable<decimal> sale_money { get; set; }
        public Nullable<decimal> push_money { get; set; }
        public Nullable<decimal> adjust_money { get; set; }
        public Nullable<decimal> total_push_money { get; set; }
        public string Id { get; set; }
    }
}
