//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tg_tourgroup_manage
    {
        public decimal tg_flow_number { get; set; }
        public string group_number { get; set; }
        public Nullable<System.DateTime> group_date { get; set; }
        public string group_type_code { get; set; }
        public string ta_code { get; set; }
        public string ta_name { get; set; }
        public string ta_type_code { get; set; }
        public string guide_code { get; set; }
        public string guide_name { get; set; }
        public string guide_tac_code { get; set; }
        public Nullable<decimal> guide_push_rate { get; set; }
        public Nullable<decimal> guide_push_money { get; set; }
        public Nullable<decimal> person_times { get; set; }
        public Nullable<decimal> discount_rate { get; set; }
        public string expostor_tac_code { get; set; }
        public string expostor { get; set; }
        public Nullable<decimal> expostor_push_rate { get; set; }
        public Nullable<decimal> expostor_push_money { get; set; }
        public string driver { get; set; }
        public string license_plate { get; set; }
        public string cars_group { get; set; }
        public string cars_type_code { get; set; }
        public Nullable<decimal> stop_charge { get; set; }
        public string customer_from { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string @operator { get; set; }
        public string assessor { get; set; }
        public string if_examine { get; set; }
        public Nullable<System.DateTime> examine_date { get; set; }
        public Nullable<System.DateTime> operator_date { get; set; }
    }
}
