//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class fb_goods_bar_code
    {
        public string goods_code { get; set; }
        public string goods_bar_code { get; set; }
        public string goods_sub_code { get; set; }
        public string goods_name { get; set; }
        public string goods_sub_name { get; set; }
        public string py_code { get; set; }
        public string gb_code { get; set; }
        public string gm_code { get; set; }
        public string gs_code { get; set; }
        public string gl_code { get; set; }
        public string owner_type { get; set; }
        public string sup_code { get; set; }
        public string op_code { get; set; }
        public Nullable<decimal> pool_rate { get; set; }
        public Nullable<decimal> pack_coef { get; set; }
        public string pack_unit_code { get; set; }
        public string qty_type { get; set; }
        public string price_type { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public Nullable<decimal> vip_price { get; set; }
        public Nullable<decimal> trade_price { get; set; }
        public string goods_state { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string Id { get; set; }
    }
}
