//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class fb_goods_archives_bar
    {
        public string goods_code { get; set; }
        public string goods_bar_code { get; set; }
        public string goods_bar_name { get; set; }
        public string pack_unit_code { get; set; }
        public Nullable<decimal> pack_coef { get; set; }
        public string qty_type { get; set; }
        public string price_type { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public Nullable<decimal> vip_price { get; set; }
        public Nullable<decimal> trade_price { get; set; }
        public Nullable<decimal> push_rate { get; set; }
        public string if_main_bar { get; set; }
        public string if_examine { get; set; }
        public string Id { get; set; }
    }
}
