//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class fb_goods_archives
    {
        public string goods_code { get; set; }
        public string goods_bar_code { get; set; }
        public string goods_sub_code { get; set; }
        public string gb_code { get; set; }
        public string gm_code { get; set; }
        public string gs_code { get; set; }
        public string gl_code { get; set; }
        public string goods_type { get; set; }
        public string check_mode { get; set; }
        public string sup_code { get; set; }
        public string op_code { get; set; }
        public Nullable<decimal> pool_rate { get; set; }
        public string goods_name { get; set; }
        public string goods_sub_name { get; set; }
        public string py_code { get; set; }
        public string goods_state { get; set; }
        public string producing_area { get; set; }
        public string article_number { get; set; }
        public string specification { get; set; }
        public string shelf_life { get; set; }
        public string pack_unit_code { get; set; }
        public string offer_mode { get; set; }
        public Nullable<decimal> pack_coef { get; set; }
        public Nullable<decimal> offer_min { get; set; }
        public Nullable<decimal> input_tax { get; set; }
        public Nullable<decimal> output_tax { get; set; }
        public Nullable<decimal> stock_upper_limit { get; set; }
        public Nullable<decimal> stock_lower_limit { get; set; }
        public string under_floor_code { get; set; }
        public string under_counter_code { get; set; }
        public string brand_code { get; set; }
        public string check_unit_code { get; set; }
        public decimal purchase_price { get; set; }
        public decimal nontax_purchase_price { get; set; }
        public Nullable<decimal> avg_cost { get; set; }
        public Nullable<decimal> nontax_avg_cost { get; set; }
        public Nullable<decimal> gross_rate { get; set; }
        public Nullable<decimal> supply_price { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public Nullable<decimal> vip_price { get; set; }
        public Nullable<decimal> trade_price { get; set; }
        public Nullable<decimal> push_rate { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string @operator { get; set; }
        public string assessor { get; set; }
        public string if_examine { get; set; }
        public Nullable<System.DateTime> examine_date { get; set; }
        public Nullable<System.DateTime> operator_date { get; set; }
    }
}
