//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_cancel_card_manage
    {
        public string cancel_number { get; set; }
        public string en_code { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public string cancel_reason { get; set; }
        public string card_number { get; set; }
        public string surface_number { get; set; }
        public string ms_code { get; set; }
        public string card_code { get; set; }
        public string card_name { get; set; }
        public string card_state { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public Nullable<System.DateTime> points_useful_life_date { get; set; }
        public Nullable<System.DateTime> card_useful_life_date { get; set; }
        public Nullable<decimal> transact_charge { get; set; }
        public Nullable<decimal> deposit_money { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string @operator { get; set; }
        public Nullable<System.DateTime> operator_date { get; set; }
    }
}
