//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_upgrade_card_detail
    {
        public string upgrade_number { get; set; }
        public string card_number { get; set; }
        public string surface_number { get; set; }
        public string card_code_old { get; set; }
        public string card_name_old { get; set; }
        public string card_code { get; set; }
        public string card_name { get; set; }
        public Nullable<decimal> deduct_points { get; set; }
        public Nullable<decimal> total_points { get; set; }
        public Nullable<decimal> exchange_points { get; set; }
        public Nullable<decimal> current_points { get; set; }
        public Nullable<decimal> clear_points { get; set; }
        public string card_state { get; set; }
        public string Id { get; set; }
    }
}
