//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class op_adjust_purchase_detail
    {
        public string adjust_number { get; set; }
        public Nullable<System.DateTime> adjust_date { get; set; }
        public string wh_code { get; set; }
        public decimal batch_number { get; set; }
        public string pi_number { get; set; }
        public System.DateTime putin_date { get; set; }
        public string goods_code { get; set; }
        public string goods_bar_code { get; set; }
        public string sup_code { get; set; }
        public Nullable<decimal> input_tax { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public Nullable<decimal> nontax_purchase_price { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public Nullable<decimal> nontax_sale_price { get; set; }
        public Nullable<decimal> purchase_qty { get; set; }
        public Nullable<decimal> stockout_qty { get; set; }
        public Nullable<decimal> stock_qty { get; set; }
        public Nullable<decimal> adjust_qty { get; set; }
        public Nullable<decimal> adjust_price { get; set; }
        public Nullable<decimal> adjust_diff { get; set; }
        public Nullable<decimal> adjust_money { get; set; }
        public string if_ablebalance { get; set; }
        public Nullable<decimal> adjust_ba_money { get; set; }
        public string if_balance { get; set; }
        public string ba_number { get; set; }
        public Nullable<decimal> ba_money { get; set; }
        public Nullable<System.DateTime> produce_date { get; set; }
        public string Id { get; set; }
    }
}
