//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class op_allot_detail
    {
        public string al_number { get; set; }
        public string goods_code { get; set; }
        public string goods_bar_code { get; set; }
        public string specification { get; set; }
        public string pack_unit_code { get; set; }
        public Nullable<decimal> stock_qty { get; set; }
        public Nullable<decimal> pack_qty { get; set; }
        public Nullable<decimal> pack_coef { get; set; }
        public Nullable<decimal> allot_qty { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public decimal purchase_price { get; set; }
        public decimal nontax_purchase_price { get; set; }
        public Nullable<decimal> allot_money { get; set; }
        public Nullable<decimal> nontax_allot_money { get; set; }
        public Nullable<decimal> sale_money { get; set; }
        public Nullable<decimal> nontax_sale_money { get; set; }
        public string Id { get; set; }
    }
}
