//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbcatedt
    {
        public string pbe_name { get; set; }
        public string pbe_edit { get; set; }
        public short pbe_type { get; set; }
        public Nullable<int> pbe_cntr { get; set; }
        public short pbe_seqn { get; set; }
        public Nullable<int> pbe_flag { get; set; }
        public string pbe_work { get; set; }
    }
}
