//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_pa_pos
    {
        public string posid { get; set; }
        public string pos_name { get; set; }
        public string pos_ip { get; set; }
        public string pos_state { get; set; }
        public string wh_code { get; set; }
        public string cd_type { get; set; }
        public string cd_port { get; set; }
        public string p_type { get; set; }
        public string p_port { get; set; }
        public Nullable<decimal> p_width { get; set; }
        public string p_type1 { get; set; }
        public string p_port1 { get; set; }
        public Nullable<decimal> p_width1 { get; set; }
        public string cb_type { get; set; }
        public string cb_port { get; set; }
    }
}
