//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_pa_saleset
    {
        public Nullable<decimal> mantissa { get; set; }
        public string mantissa_mode { get; set; }
        public string if_return_sale { get; set; }
        public string if_negative_stock { get; set; }
        public string if_return_payway { get; set; }
        public string if_salesman { get; set; }
        public string if_counter { get; set; }
        public string print_type { get; set; }
        public string if_bind { get; set; }
        public string if_entertopay { get; set; }
        public string if_entertormb { get; set; }
        public string if_english_sale { get; set; }
        public string title1 { get; set; }
        public string title2 { get; set; }
        public string title3 { get; set; }
        public string title4 { get; set; }
        public string title5 { get; set; }
        public string pagefoot1 { get; set; }
        public string pagefoot2 { get; set; }
        public string pagefoot3 { get; set; }
        public string pagefoot4 { get; set; }
        public string pagefoot5 { get; set; }
        public string if_en_name { get; set; }
        public string if_b_name { get; set; }
        public string if_goods_code { get; set; }
        public string if_goods_bar_code { get; set; }
        public string if_goods_name { get; set; }
        public string if_goods_sub_name { get; set; }
        public string if_pack_unit { get; set; }
        public string if_prepaid { get; set; }
        public string Id { get; set; }
    }
}
