//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_sheet_promotion_goods
    {
        public string sp_number { get; set; }
        public string sp_begin_date { get; set; }
        public string sp_end_date { get; set; }
        public string sp_begin_time { get; set; }
        public string sp_end_time { get; set; }
        public string sp_w1 { get; set; }
        public string sp_w2 { get; set; }
        public string sp_w3 { get; set; }
        public string sp_w4 { get; set; }
        public string sp_w5 { get; set; }
        public string sp_w6 { get; set; }
        public string sp_w7 { get; set; }
        public Nullable<decimal> sale_money { get; set; }
        public Nullable<decimal> sale_discount_rate { get; set; }
        public string comment { get; set; }
        public string sys_guid { get; set; }
        public string Id { get; set; }
    }
}
