//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_enterprise_archives
    {
        public string en_code { get; set; }
        public string en_name { get; set; }
        public string en_com_name { get; set; }
        public string en_type { get; set; }
        public string en_character { get; set; }
        public Nullable<decimal> deal_area { get; set; }
        public string register_address { get; set; }
        public string current_version { get; set; }
        public string last_version { get; set; }
        public string Id { get; set; }
    }
}
