//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_operation_flow_detail
    {
        public string operation_number { get; set; }
        public string operation_name { get; set; }
        public string s_number { get; set; }
        public string window_name { get; set; }
        public string current_s_number { get; set; }
        public string function_code { get; set; }
        public string current_function_code { get; set; }
        public string column_name { get; set; }
        public string next_s_number { get; set; }
        public string current_state { get; set; }
        public string operation_state { get; set; }
        public string operation_result { get; set; }
        public string operation_opinion { get; set; }
        public string @operator { get; set; }
        public Nullable<System.DateTime> operator_date { get; set; }
        public string statement { get; set; }
        public string statement_state { get; set; }
    }
}
