//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tf_data_object
    {
        public string object_id { get; set; }
        public string object_name { get; set; }
        public string object_main { get; set; }
        public string object_maincolumn { get; set; }
        public string object_foreigncolumn { get; set; }
        public Nullable<bool> object_isinsert { get; set; }
        public Nullable<bool> object_isdelete { get; set; }
        public Nullable<bool> object_isupdate { get; set; }
        public string object_dump { get; set; }
        public string object_keycolumn { get; set; }
        public string object_branchcodecolumn { get; set; }
        public Nullable<bool> object_isdeletedump { get; set; }
        public string object_description { get; set; }
        public string object_direction { get; set; }
        public Nullable<bool> object_istransfer { get; set; }
        public string object_condition { get; set; }
        public Nullable<int> object_order { get; set; }
        public string Id { get; set; }
    }
}
