//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tf_data_property
    {
        public string property_id { get; set; }
        public string property_object { get; set; }
        public string property_name { get; set; }
        public string property_type { get; set; }
        public Nullable<bool> property_iskey { get; set; }
        public Nullable<bool> property_isnullable { get; set; }
        public Nullable<bool> property_isunqueindex { get; set; }
        public Nullable<bool> property_istransfer { get; set; }
        public string property_description { get; set; }
        public string property_condition { get; set; }
        public string Id { get; set; }
    }
}
