//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tg_travel_archives
    {
        public string ta_code { get; set; }
        public string ta_name { get; set; }
        public string py_code { get; set; }
        public string ta_type_code { get; set; }
        public Nullable<decimal> push_rate { get; set; }
        public Nullable<decimal> push_money { get; set; }
        public Nullable<decimal> push_money_account { get; set; }
        public Nullable<decimal> ta_returns_rate { get; set; }
        public string functionary { get; set; }
        public string functionary_phone { get; set; }
        public string linkman { get; set; }
        public string contact_phone { get; set; }
        public string contact_address { get; set; }
        public string office_phone { get; set; }
        public string fax_phone { get; set; }
        public string e_mail { get; set; }
        public string postalcode { get; set; }
        public string open_account { get; set; }
        public string bank_account { get; set; }
        public string tax_number { get; set; }
        public string print_type { get; set; }
        public string if_print { get; set; }
        public string cars_type { get; set; }
        public string comment { get; set; }
    }
}
