//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiQiWorkFlow.Domain.Basement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ws_wholesale_manage
    {
        public string ws_number { get; set; }
        public Nullable<System.DateTime> ws_date { get; set; }
        public string order_number { get; set; }
        public string cust_code { get; set; }
        public string ws_type { get; set; }
        public string ws_organ { get; set; }
        public string pay_mode { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
        public string wh_code { get; set; }
        public string salesman { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string @operator { get; set; }
        public string assessor { get; set; }
        public string if_examine { get; set; }
        public Nullable<System.DateTime> examine_date { get; set; }
        public Nullable<System.DateTime> operator_date { get; set; }
    }
}
